# This file was generated by GoReleaser. DO NOT EDIT.
cask "briefkasten" do
  version "0.31.1"

  on_macos do
    on_intel do
      sha256 "774202b2427ce929e9aa331569403cf86cad41ee0c6ed82fea884e8df92c61cd"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "45c1a2d6b5ef1c212b377631e41f31efab3a1b37924495b96fbfda8eec603592"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ab5e9efa90ecc679dbac2306c89b72b615a5d4add4c264a9db95bcd4f9473b0"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e14510ecba5cfe4b6fe8e9bc2a1f20d3486aec36f6d4182394d451ee42c364da"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_linux_arm64.tar.gz"
    end
  end

  name "briefkasten"
  desc "A mailbox as an MCP server"
  homepage "https://github.com/klarlabs-studio/briefkasten"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "briefkasten"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/briefkasten"]
    end
  end

  # No zap stanza required

end
