# This file was generated by GoReleaser. DO NOT EDIT.
cask "briefkasten" do
  version "0.31.0"

  on_macos do
    on_intel do
      sha256 "b5c578444b86ef3d77261da751be5b6b4dbfe2f3f7e763ee3f905ec49309af5d"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "beb09eaed2ed72ce9ff83bab91d9439a7c3445f70232cfbc39d78861ff0a5a0f"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1f5f61449b441256b8cbb3500a4ac28199f3980604d3243712cd2b6083529331"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "dace78dffc7f93188ccf2e1fbbdfc526dc84634beba79df9f256b1e44b671a0e"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_linux_arm64.tar.gz"
    end
  end

  name "briefkasten"
  desc "A mailbox as an MCP server"
  homepage "https://github.com/klarlabs-studio/briefkasten"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "briefkasten"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/briefkasten"]
    end
  end

  # No zap stanza required

end
