# This file was generated by GoReleaser. DO NOT EDIT.
cask "briefkasten" do
  version "0.21.0"

  on_macos do
    on_intel do
      sha256 "44b4c349246526865a720981470aa1b7753f4ff4d6fef3c515fbba1177557f0e"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "93d7d9ca8c3ea54df3ce0327e92d96aecd25bf918e33f2af4e1baaa3549064ae"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eaa6a1d7ce41c486424eb5a29e81c41d10f29d457befe60f7206e95c0b07b4dd"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f4ef5ceed5869418d7a8912239aaf80219bed4277338fa9c2dcbff9e9343d46f"
      url "https://github.com/klarlabs-studio/briefkasten/releases/download/v#{version}/briefkasten_#{version}_linux_arm64.tar.gz"
    end
  end

  name "briefkasten"
  desc "A mailbox as an MCP server"
  homepage "https://github.com/klarlabs-studio/briefkasten"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "briefkasten"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/briefkasten"]
    end
  end

  # No zap stanza required

end
