# This file was generated by GoReleaser. DO NOT EDIT.
cask "heartbeat" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "0378bf07f31706b32d4ddb99506361d15cbe2c446acaea51971231498f0e0e22"
      url "https://github.com/klarlabs-studio/heartbeat/releases/download/v#{version}/heartbeat_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1fcc97b9b81660451d6ecdc87acb62dffc87c38e31a1d04bb24e9e53913dd534"
      url "https://github.com/klarlabs-studio/heartbeat/releases/download/v#{version}/heartbeat_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f29283b60f192ba895ffd09412f2d90db29d86248b7f2a480c441231b058b6dd"
      url "https://github.com/klarlabs-studio/heartbeat/releases/download/v#{version}/heartbeat_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "fa12d84ddf01a0261f952a68f34293a8732de5525e937df354cca1c392aa1a23"
      url "https://github.com/klarlabs-studio/heartbeat/releases/download/v#{version}/heartbeat_linux_arm64.tar.gz"
    end
  end

  name "heartbeat"
  desc "MCP server for running team health checks with AI agents"
  homepage "https://github.com/klarlabs-studio/heartbeat"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heartbeat"

  # No zap stanza required

end
