# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiln" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "abd609b8761cf14d1a9199717b7aeee3b73b7b3cd8e046e57d5572922ffb51a1"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "02ccf2a9f36b70f6dec10031ec89e6282697c5361488d7e4b5383e858dd7ac57"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2fd6d070b682194d188b66d52d0f0ae3a56abbca70cc7b1319b0153aa3ecc6b7"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "93a88ac4c51c8a835d8ef44110f07029a09541379dae9f18c4042b22e65e3d40"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kiln"
  desc "Signed-artifact factory: prove a commit, build it, sign it, attest it"
  homepage "https://github.com/klarlabs-studio/kiln"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiln"
  binary "kilnd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiln"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kilnd"]
    end
  end

  # No zap stanza required

end
