# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiln" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "edc46d794141e08a65f57546f1caa17b799cda259efabd5e189c2e482120f60b"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4d17958fd01bc46f931d86a887d49c95057f1b3582e9bb5f65d6acd4244f1610"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cedf8549e85b8416666c75ff5f558a4bb0066ba4eba0be429622bc9470f57619"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d439f4cf27f153701c379fb990c357872c146e3e5749ebcee52f3ece8b120547"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kiln"
  desc "Signed-artifact factory: prove a commit, build it, sign it, attest it"
  homepage "https://github.com/klarlabs-studio/kiln"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiln"
  binary "kilnd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiln"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kilnd"]
    end
  end

  # No zap stanza required

end
