# This file was generated by GoReleaser. DO NOT EDIT.
cask "kiln" do
  version "0.3.5"

  on_macos do
    on_intel do
      sha256 "5a2cee372e37e884dc50a1f4cb0cb532b94169dd5935c7299fef2a86a113a23c"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c74307c07808142e03138c108b3f0603f6f60c04395bda71bacf91edbbd7cb6a"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9da2f76217815178b93e0e0eac59ae3f502b761791d915be76369948957aedcc"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0ee192acae1eac0109b69ecf1d43aa802157b69cb9888364268dcd6dd5d506d"
      url "https://github.com/klarlabs-studio/kiln/releases/download/v#{version}/kiln_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kiln"
  desc "Signed-artifact factory: prove a commit, build it, sign it, attest it"
  homepage "https://github.com/klarlabs-studio/kiln"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kiln"
  binary "kilnd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kiln"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kilnd"]
    end
  end

  # No zap stanza required

end
