# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemos" do
  version "0.120.0"

  on_macos do
    on_intel do
      sha256 "d8b157b83bdf042cfd6882084227cd6aeb1b33111b62ce9c7f6d7e01e8020e18"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3aa83cd1f663cc19a25cfbb394f646d21fa8d4fe059049d7bbcb75bb5f8cb6f6"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e9c4e6d0eb2752ba3dbf06f5d7bca423c7802a507703c41f3cbf2005337b65b"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0e1af0d19fd53e27d228a5845b8a5351af67b74f9183020ffd5f9f014b08400f"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemos"
  desc "Local-first evidence layer that grounds AI in truth"
  homepage "https://github.com/klarlabs-studio/mnemos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemos"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemos"]
    end
  end

  # No zap stanza required

end
