# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemos" do
  version "0.112.0"

  on_macos do
    on_intel do
      sha256 "97d461141919fa283e8cc162761e54a6d364733511702e0a27705f216cafed7b"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5b7aae496adef83287ab600be8c7de3dd5de29a8d069b1703b1e3a7f99b31b3"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4b96e96c0bb1081fc914a6371bef5c6768b181c9485f8942bad594192798a57f"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9275d3310704a2f16f6242e15e1abd61f1f25ff6009eae2ce22f06c799a53d0f"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemos"
  desc "Local-first evidence layer that grounds AI in truth"
  homepage "https://github.com/klarlabs-studio/mnemos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemos"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemos"]
    end
  end

  # No zap stanza required

end
