# This file was generated by GoReleaser. DO NOT EDIT.
cask "mnemos" do
  version "0.121.0"

  on_macos do
    on_intel do
      sha256 "e6d49d286c07292c96463cb6b5e12c0656ff86e6811ccff2842c63e725aae9df"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1a4a42c24e0117b4212d4c353462ab93073354fef4280bbbe0b10ab5ff62f9c"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eec84978db3f8727c3cc90b4d8b4900fef4d4dd495c0b8446d2bb3ba7757029b"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "985222bed22cf44000dca6b9c5a21ce7ce41614b1b5dc64cfe6aff90485801ab"
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v#{version}/mnemos_#{version}_linux_arm64.tar.gz"
    end
  end

  name "mnemos"
  desc "Local-first evidence layer that grounds AI in truth"
  homepage "https://github.com/klarlabs-studio/mnemos"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mnemos"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mnemos"]
    end
  end

  # No zap stanza required

end
