# This file was generated by GoReleaser. DO NOT EDIT.
cask "roady" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "52903cbbd840651fb3af51ed78cc632e13afc067b5a2354790de01f5de531206"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ea958ce12693fa14ed4dd6b1c7c8a96c8f1ec39c0003a6d3d76cca5180d25d8e"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bb58c150e161d2630ee940fad1fe65c55bf3c3e22d06f6847fc9766895dbd254"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "589b1da9c2c504516ff6d5bda859315cc89df247c99b997573c2a2fa85c7eade"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Linux_arm64.tar.gz"
    end
  end

  name "roady"
  desc "A planning-first system of record for software work."
  homepage "https://felixgeelhaar.github.io/roady/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "roady"
  binary "roady-plugin-linear"
  binary "roady-plugin-jira"
  binary "roady-plugin-github"
  binary "roady-plugin-asana"
  binary "roady-plugin-notion"
  binary "roady-plugin-trello"
  binary "roady-plugin-mock"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
