# This file was generated by GoReleaser. DO NOT EDIT.
cask "roady" do
  version "0.18.0"

  on_macos do
    on_intel do
      sha256 "3016948ca68f58fe403f5008fb1e0838153163786c444b6492b2fcb7bc26e83e"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a18c6076704c4cd20a65d4f74ec8a8d416db85751625a8575e63d5cab5ed2215"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6c2ac986354c7274ef559532753b36e33d33dedefa794e6ea1a180ab6ac0619e"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "85cdba09a8188896f08644cf99816d628556eb6e78377030cc0fc28beffd4936"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Linux_arm64.tar.gz"
    end
  end

  name "roady"
  desc "A planning-first system of record for software work."
  homepage "https://felixgeelhaar.github.io/roady/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "roady"
  binary "roady-plugin-linear"
  binary "roady-plugin-jira"
  binary "roady-plugin-github"
  binary "roady-plugin-asana"
  binary "roady-plugin-notion"
  binary "roady-plugin-trello"
  binary "roady-plugin-mock"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
