# This file was generated by GoReleaser. DO NOT EDIT.
cask "roady" do
  version "0.14.1"

  on_macos do
    on_intel do
      sha256 "fcfab262d86052bdfa58b5494bd83f0949e8f19931d8776ce382876d9060767f"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a7c48e2bce6bf60142ec94c830c8111f054a6a733da4925ddbfd7cf13745218f"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3066afbedf201e22d20260fd0074f1a528bdc829311071679fe5d7e4e88b4dc8"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "314a308f6f8ec16d081f3eaef4383d8eff1ddb6ebb0b3d16f645321f53786c3e"
      url "https://github.com/klarlabs-studio/roady/releases/download/v#{version}/roady_Linux_arm64.tar.gz"
    end
  end

  name "roady"
  desc "A planning-first system of record for software work."
  homepage "https://felixgeelhaar.github.io/roady/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "roady"
  binary "roady-plugin-linear"
  binary "roady-plugin-jira"
  binary "roady-plugin-github"
  binary "roady-plugin-asana"
  binary "roady-plugin-notion"
  binary "roady-plugin-trello"
  binary "roady-plugin-mock"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

end
