# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout-mcp" do
  version "1.15.3"

  on_macos do
    on_intel do
      sha256 "d5c279ab8850511966aac58f8062f3822e1a97d21fe1eac62a296b21e05a4dc9"
      url "https://github.com/klarlabs-studio/scout/releases/download/v#{version}/scout_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3fd28468a8665cdc8a8d47405ea34ca5e8b7e70ecba23692d53dbe419d057c03"
      url "https://github.com/klarlabs-studio/scout/releases/download/v#{version}/scout_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3c6d1967d69ae705142621274d1ee1e64ec6470284ae7a3e38cd8f3e8c09b7ae"
      url "https://github.com/klarlabs-studio/scout/releases/download/v#{version}/scout_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e66f0c4bcc5d31b4443420fd0ead59e0c0cc61024cc3a8df96862e446957c67d"
      url "https://github.com/klarlabs-studio/scout/releases/download/v#{version}/scout_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scout-mcp"
  desc "MCP server for AI-powered browser automation"
  homepage "https://github.com/klarlabs-studio/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scout"]
    end
  end

  # No zap stanza required

end
