# This file was generated by GoReleaser. DO NOT EDIT.
cask "scout" do
  version "1.15.2"

  on_macos do
    on_intel do
      sha256 "2bb0127bbf59e0cf187abbfc2adedfdc9a86ea0833bab55ba220c65354a74430"
      url "https://github.com/klarlabs-studio/scout/releases/download/v#{version}/scout_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "17000032d1d2d088d632e7d84ac29c2402a68b96123e9103efe69749ea3ca538"
      url "https://github.com/klarlabs-studio/scout/releases/download/v#{version}/scout_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ab4418cacf12652d02d7b56e76a444b2264a266b7a86221e413391c8ed6fd9cb"
      url "https://github.com/klarlabs-studio/scout/releases/download/v#{version}/scout_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "08a4f38ca784e279d7a51b67e20f79d698d672b2b02cffccade728a719eb8448"
      url "https://github.com/klarlabs-studio/scout/releases/download/v#{version}/scout_#{version}_linux_arm64.tar.gz"
    end
  end

  name "scout"
  desc "MCP server for AI-powered browser automation"
  homepage "https://github.com/klarlabs-studio/scout"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scout"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scout"]
    end
  end

  # No zap stanza required

end
