# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenops" do
  version "0.72.5"

  on_macos do
    on_arm do
      sha256 "a07fa7e2403a080db17cb5d5e076eba8dc4d86c45dc2e5c9639d1e3607dcf0e6"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "211d3b29558b301c216b22c12ba61d273fdf95bded4809afa6c36248d55f328f"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "636da4df3fe8aef474b0ee9ac92e236cf84a8ab006f60e0c2517ef41d15b5ef7"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "28bd4303d9109b8477a290e36c130273c1202e95cc65f5dc3966f820bdc22e2c"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tokenops"
  desc "Open-source operational intelligence layer for AI systems"
  homepage "https://github.com/klarlabs-studio/tokenops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenops"
  binary "tokenopsd"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
    unit = if OS.mac?
      File.expand_path("~/Library/LaunchAgents/de.klarlabs.tokenops.plist")
    else
      File.expand_path("~/.config/systemd/user/tokenops.service")
    end
    if File.exist?(unit)
      bin = "#{HOMEBREW_PREFIX}/bin/tokenops"
      system_command bin, args: ["daemon", "install", "--bin", bin], print_stdout: true, print_stderr: true, must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    First install: supervise the ingestion daemon so it survives reboot:

      tokenops daemon install

    Upgrades restart an installed daemon on the new version by themselves.

    `tokenops serve` is the MCP server and does not ingest.
    `tokenops start` runs the pollers; the unit above keeps it alive.
  EOS
end
