# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenops" do
  version "0.53.0"

  on_macos do
    on_arm do
      sha256 "8383e7a465de03bf530c449140c05c6cc4d093e5bd2817e6b1e4534b4128ae25"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "87804dc12ac4f70cb7dc3053f8159f208c88ee01af9c484c7a0908936af3bf01"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ded46aac0a0b5809cb44ea3482a726cbd4541e04b218da9f87405801b5e6b9cd"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "feacdb40257a58be640ec6719580269f855d3c89debd7d874a58c3c698e4b2e0"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tokenops"
  desc "Open-source operational intelligence layer for AI systems"
  homepage "https://github.com/klarlabs-studio/tokenops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenops"
  binary "tokenopsd"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Supervise the ingestion daemon so it survives reboot:

      tokenops daemon install

    `tokenops serve` is the MCP server and does not ingest.
    `tokenops start` runs the pollers; the unit above keeps it alive.
  EOS
end
