# This file was generated by GoReleaser. DO NOT EDIT.
cask "tokenops" do
  version "0.95.0"

  on_macos do
    on_arm do
      sha256 "f85ecffa4fb32cb91a48c54e0023db797756a48f732c12dd10d7c5d816beeb55"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6f9a2baf81a9094654426a60a0cf039bfa5197bb177845a6f9bbd3ceef2813ab"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aa6de89a9dab4cb794a3f21d71bff9016251c73d7e1ed809928a59bd3b827ec1"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "465692fe98d740674f4cba8d56d08a9d8dd177c5c0a69d33e04cefe36404c417"
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v#{version}/tokenops_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tokenops"
  desc "Open-source operational intelligence layer for AI systems"
  homepage "https://github.com/klarlabs-studio/tokenops"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tokenops"
  binary "tokenopsd"

  postflight do
    if OS.mac?
      system_command "xattr", args: ["-dr", "com.apple.quarantine", staged_path]
    end
    unit = if OS.mac?
      File.expand_path("~/Library/LaunchAgents/de.klarlabs.tokenops.plist")
    else
      File.expand_path("~/.config/systemd/user/tokenops.service")
    end
    if File.exist?(unit)
      bin = "#{HOMEBREW_PREFIX}/bin/tokenops"
      system_command bin, args: ["daemon", "install", "--bin", bin], print_stdout: true, print_stderr: true, must_succeed: false
    end
  end

  # No zap stanza required

  caveats <<~EOS
    First install: supervise the ingestion daemon so it survives reboot:

      tokenops daemon install

    Upgrades restart an installed daemon on the new version by themselves.

    `tokenops serve` is the MCP server and does not ingest.
    `tokenops start` runs the pollers; the unit above keeps it alive.
  EOS
end
