# This file was generated by GoReleaser. DO NOT EDIT.
cask "warden" do
  version "0.22.0"

  on_macos do
    on_intel do
      sha256 "9d3e43fcc4b9d7430330c2e78e80a74fd90e947be1c56fd6ae9b26c244d689f2"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "874f17a8a53ab62ee618cb09b5bc9708dd6f5ef0c39a0554da4582311c277949"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "476be67a3f8cf6b594ad19bee953e9e9807005e7bf87c0146b0ea6108ae29407"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1ba2b8de355acdaf25b2a5e7ddb7fdecaeef60575db3e581c6050e18d8ac1fbc"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_arm64.tar.gz"
    end
  end

  name "warden"
  desc "Configurable git commit/push gate — native hooks, worktree isolation, cryptographic provenance"
  homepage "https://go.klarlabs.de/warden"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warden"]
    end
  end

  # No zap stanza required

end
