# This file was generated by GoReleaser. DO NOT EDIT.
cask "warden" do
  version "0.32.2"

  on_macos do
    on_intel do
      sha256 "5813b705f8021bc012437e39fbfdea329cafd7b578a901b419acb36bde7340fd"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5f2d108fe39dc7157665c7b97d655f921922caead3ddfbe64fae49baff1ae1eb"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2dcbe82e13e53a117c8e62bf185401ed915d739c6c602834254b7eaf47889e09"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c5f04d5ec3dd608d28e459d275de1137b3990569fd33aa8510965df3425a3618"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_arm64.tar.gz"
    end
  end

  name "warden"
  desc "Configurable git commit/push gate — native hooks, worktree isolation, cryptographic provenance"
  homepage "https://go.klarlabs.de/warden"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warden"]
    end
  end

  # No zap stanza required

end
