# This file was generated by GoReleaser. DO NOT EDIT.
cask "warden" do
  version "0.21.1"

  on_macos do
    on_intel do
      sha256 "12a5ed7deb5a4ad1585844c99f1ae76bd0bde7d3645ed1a5ab7e2fc58c57e7dd"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "10f3a765e77934094b424fdae701f67ec1e55045b690cbfd6781ae94eaab7007"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7e2d9af7f2f94e97f435bc9281c56f4e770f547ee0afd51692bbef1a51e86e75"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "44aee2169e080fb70fb1ece77d238db2020427e3f8acb9f30094d6ac2e94067b"
      url "https://github.com/klarlabs-studio/warden/releases/download/v#{version}/warden_#{version}_linux_arm64.tar.gz"
    end
  end

  name "warden"
  desc "Configurable git commit/push gate — native hooks, worktree isolation, cryptographic provenance"
  homepage "https://go.klarlabs.de/warden"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "warden"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/warden"]
    end
  end

  # No zap stanza required

end
