# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemos < Formula
  desc "Local-first evidence layer that grounds AI in truth"
  homepage "https://github.com/klarlabs-studio/mnemos"
  version "0.30.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.30.0/mnemos_0.30.0_darwin_amd64.tar.gz"
      sha256 "073127b689d48018820a9349f175320e0b7f104417a30e60552961c2781d99ab"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.30.0/mnemos_0.30.0_darwin_arm64.tar.gz"
      sha256 "9979e3f1c1574e9fdc01c040450b8ca282524fee4a9242c33d6884df2e6eb8fc"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.30.0/mnemos_0.30.0_linux_amd64.tar.gz"
      sha256 "1568ed9d9a154f5f0403a05c7d8173ca436fc7a746867464f38c95561159e60d"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.30.0/mnemos_0.30.0_linux_arm64.tar.gz"
      sha256 "1ca15c7d309223f3944902031c30cacf5247e68198ff4d477f5f30b3a6617323"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  test do
    system bin/"mnemos", "--version"
  end
end
