# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemos < Formula
  desc "Local-first evidence layer that grounds AI in truth"
  homepage "https://github.com/klarlabs-studio/mnemos"
  version "0.48.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.48.0/mnemos_0.48.0_darwin_amd64.tar.gz"
      sha256 "9f46455f33d732234e49f09a1747df8e10a093165eac7f190a03196b40e92108"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.48.0/mnemos_0.48.0_darwin_arm64.tar.gz"
      sha256 "afa4de4e1e74c41e5db0e23a9751f6e4e313de8356b8590f7f35107dcd7d0b75"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.48.0/mnemos_0.48.0_linux_amd64.tar.gz"
      sha256 "74c576dd03b393e68e3f520fbe6b542699c9de4ddb15c66ec7c74e93ed5c4783"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.48.0/mnemos_0.48.0_linux_arm64.tar.gz"
      sha256 "9f6af17ad8129313a87124a5bca1ea8e79481f4ebb79fda84cce4503b42086a5"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  test do
    system bin/"mnemos", "--version"
  end
end
