# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mnemos < Formula
  desc "Local-first evidence layer that grounds AI in truth"
  homepage "https://github.com/klarlabs-studio/mnemos"
  version "0.85.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.85.1/mnemos_0.85.1_darwin_amd64.tar.gz"
      sha256 "b8e22d1f17cc075af39bb3ca1db8ac74d570e1792d3bc1e726e92b70029df2f4"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.85.1/mnemos_0.85.1_darwin_arm64.tar.gz"
      sha256 "008cebbd481fd7d0b830a3c0f4f3ecb33531f33869437f3a671946c79c51598d"

      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.85.1/mnemos_0.85.1_linux_amd64.tar.gz"
      sha256 "c90d9fce2fc60efe937836204c5daf23d59165c033a887758b523dcefffacaa3"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/Mnemos/releases/download/v0.85.1/mnemos_0.85.1_linux_arm64.tar.gz"
      sha256 "813130b5a8ebef58a96a80ac953cff02b94a11fda0fadcc0aa80e03c812ee92e"
      define_method(:install) do
        bin.install "mnemos"
      end
    end
  end

  test do
    system bin/"mnemos", "--version"
  end
end
