# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roady < Formula
  desc "A planning-first system of record for software work."
  homepage "https://felixgeelhaar.github.io/roady/"
  version "0.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klarlabs-studio/roady/releases/download/v0.13.1/roady_Darwin_x86_64.tar.gz"
      sha256 "9c8384750fb6655fcebec7530f5617c7084b0110bf53227559e7942827d82250"

      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klarlabs-studio/roady/releases/download/v0.13.1/roady_Darwin_arm64.tar.gz"
      sha256 "ab803dc1b1b59612ada44d353edd7e86f6719efdfe4a2430692949afa385dbd4"

      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/roady/releases/download/v0.13.1/roady_Linux_x86_64.tar.gz"
      sha256 "a78ff0d0dad2a375a80a8926f200075ae8996560370306c9f46de5ca53855af7"
      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/roady/releases/download/v0.13.1/roady_Linux_arm64.tar.gz"
      sha256 "45c41c1cb1e63b1b27269fef99f1a0c8888707287b14b6e617b41a4b21cc972a"
      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
  end

  test do
    system "#{bin}/roady --version"
  end
end
