# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roady < Formula
  desc "A planning-first system of record for software work."
  homepage "https://felixgeelhaar.github.io/roady/"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.13.0/roady_Darwin_x86_64.tar.gz"
      sha256 "c7137e8778290a798338b64d2974ab42801bb55993d0617bfc3146565a1fce21"

      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.13.0/roady_Darwin_arm64.tar.gz"
      sha256 "9fad3a40c044750a22ad25039bd8fecac47f07e9b951b6a3c4cef5c1d0d1e57e"

      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.13.0/roady_Linux_x86_64.tar.gz"
      sha256 "a460fd568f95fce59d1590d2f3ddf0aba86908ca9bdc82cab59317e4d9a9947d"
      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/felixgeelhaar/roady/releases/download/v0.13.0/roady_Linux_arm64.tar.gz"
      sha256 "cf71bf57d03239361353944c1cb2e33a3c0d54782feaaa7ec97d13df62f31808"
      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
  end

  test do
    system "#{bin}/roady --version"
  end
end
