# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Roady < Formula
  desc "A planning-first system of record for software work."
  homepage "https://felixgeelhaar.github.io/roady/"
  version "0.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klarlabs-studio/roady/releases/download/v0.13.1/roady_Darwin_x86_64.tar.gz"
      sha256 "8b87cbdec89d1471e84a22a9bcf4c7e86be15e7e2baf5e158f57d4696e9cfb50"

      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klarlabs-studio/roady/releases/download/v0.13.1/roady_Darwin_arm64.tar.gz"
      sha256 "ec6600bc6f08c55fe53de59a045b53dc13d8e3d8bb0e466cdd29600b4a5ec0ad"

      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/roady/releases/download/v0.13.1/roady_Linux_x86_64.tar.gz"
      sha256 "9d06d3df7aee6889c634475f5699195a9c3e3505871a557fd6ed4aefcc4d77bb"
      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/roady/releases/download/v0.13.1/roady_Linux_arm64.tar.gz"
      sha256 "62cea7e5354858c60cd5f738cc6584b117d433358a1019be21a84e967885bc28"
      define_method(:install) do
        bin.install "roady"
        bin.install "roady-plugin-linear"
        bin.install "roady-plugin-jira"
        bin.install "roady-plugin-github"
        bin.install "roady-plugin-asana"
        bin.install "roady-plugin-notion"
        bin.install "roady-plugin-trello"
        bin.install "roady-plugin-mock"
      end
    end
  end

  test do
    system "#{bin}/roady --version"
  end
end
