# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scout < Formula
  desc "MCP server for AI-powered browser automation"
  homepage "https://github.com/klarlabs-studio/scout"
  version "1.12.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klarlabs-studio/scout/releases/download/v1.12.1/scout_1.12.1_darwin_amd64.tar.gz"
      sha256 "5e29c7c027490d42790458372630b8d6ba19bd03dd1c71b61e4ead396d8ffab1"

      define_method(:install) do
        bin.install "scout"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klarlabs-studio/scout/releases/download/v1.12.1/scout_1.12.1_darwin_arm64.tar.gz"
      sha256 "df484c260c8aadcf19801666a36cb9494efd9b0b5d5fdb0b66a933e52286936f"

      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/scout/releases/download/v1.12.1/scout_1.12.1_linux_amd64.tar.gz"
      sha256 "a237ab6208f129eddbb5e6cefee1499461eb2451779adff5bd2624b80a987f9f"
      define_method(:install) do
        bin.install "scout"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/scout/releases/download/v1.12.1/scout_1.12.1_linux_arm64.tar.gz"
      sha256 "0c2c28ad039e16987e86cc0537495c5aa5149e6f8fffdf3e60c529ecc3a9ebb5"
      define_method(:install) do
        bin.install "scout"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/scout --version")
  end
end
