# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenops < Formula
  desc "Open-source operational intelligence layer for AI systems"
  homepage "https://github.com/klarlabs-studio/tokenops"
  version "0.42.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.42.1/tokenops_0.42.1_darwin_amd64.tar.gz"
      sha256 "0f03e2cab501e8cd97a0ad2a0374c060f7e578f4516187ec438aa3b9b4adb70d"

      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.42.1/tokenops_0.42.1_darwin_arm64.tar.gz"
      sha256 "a995db78b7b95e4f086b22c2aa971e70064d079090af4963dce35279885efbcc"

      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.42.1/tokenops_0.42.1_linux_amd64.tar.gz"
      sha256 "d366d363f637a24da2a31b74f720c7dc61fab654a4cabe553125242061f14b1a"
      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.42.1/tokenops_0.42.1_linux_arm64.tar.gz"
      sha256 "9f9f8629f59f396c056f19da7cb061e893834122d4cb99114b917d47d6579769"
      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
  end

  test do
    system "#{bin}/tokenops", "version"
    system "#{bin}/tokenopsd", "version"
  end
end
