# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tokenops < Formula
  desc "Open-source operational intelligence layer for AI systems"
  homepage "https://github.com/klarlabs-studio/tokenops"
  version "0.42.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.42.0/tokenops_0.42.0_darwin_amd64.tar.gz"
      sha256 "91f1c4edd42383359e3111275e316f857801b324dd57b97aea43a738c16ff6a1"

      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.42.0/tokenops_0.42.0_darwin_arm64.tar.gz"
      sha256 "112c7e506efb9a009a4cf67aa72934c22229de8d90131dd75f8eecb517752130"

      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.42.0/tokenops_0.42.0_linux_amd64.tar.gz"
      sha256 "c56eb283894ee5363bb3cab30cc1b22d1ff355669b2266e9d3a0419fc244ceec"
      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/klarlabs-studio/tokenops/releases/download/v0.42.0/tokenops_0.42.0_linux_arm64.tar.gz"
      sha256 "1a4f326b7e505eaeb9a00a245081ba8b58979343b5f0a438c55bc7a6d1ff7ee2"
      define_method(:install) do
        bin.install "tokenops"
        bin.install "tokenopsd"
      end
    end
  end

  test do
    system "#{bin}/tokenops", "version"
    system "#{bin}/tokenopsd", "version"
  end
end
